#https://archive.ics.uci.edu/ml/datasets/heart+disease

This database contains 13 attributes (which have been extracted from
a larger set of 75)       
  

Attribute Information:
------------------------
      -- 1. age       
      -- 2. sex       
      -- 3. chest pain type  (4 values)       
      -- 4. resting blood pressure  
      -- 5. serum cholestoral in mg/dl      
      -- 6. fasting blood sugar > 120 mg/dl       
      -- 7. resting electrocardiographic results  (values 0,1,2) 
      -- 8. maximum heart rate achieved  
      -- 9. exercise induced angina    
      -- 10. oldpeak = ST depression induced by exercise relative to rest   
      -- 11. the slope of the peak exercise ST segment     
      -- 12. number of major vessels (0-3) colored by flourosopy        
      -- 13.  thal: 3 = normal; 6 = fixed defect; 7 = reversable defect     

Attributes types
-----------------

Real: 1,4,5,8,10,12
Ordered:11,
Binary: 2,6,9
Nominal:7,3,13

Variable to be predicted
------------------------
Absence (1) or presence (2) of heart disease

Cost Matrix

	 abse  pres
absence	  0	1
presence  5	0

where the rows represent the true values and the columns the predicted.

No missing values.

270 observations

In [12]:
# Download data
import pandas as pd

url = "http://archive.ics.uci.edu/ml/machine-learning-databases/statlog/heart/heart.dat"

cols = ['age','sex','chestpain','restBP','chol','sugar','ecg',
        'maxhr','angina','dep','exercise','fluor','thal','diagnosis']

table = pd.read_csv(url, sep='\s+', names=cols)

table.describe()

,age,sex,chestpain,restBP,chol,sugar,ecg,maxhr,angina,dep,exercise,fluor,thal,diagnosis
count,270.000000,270.000000,270.000000,270.000000,270.000000,270.000000,270.000000,270.000000,270.000000,270.00000,270.000000,270.000000,270.000000,270.000000
mean,54.433333,0.677778,3.174074,131.344444,249.659259,0.148148,1.022222,149.677778,0.329630,1.05000,1.585185,0.670370,4.696296,1.444444
std,9.109067,0.468195,0.950090,17.861608,51.686237,0.355906,0.997891,23.165717,0.470952,1.14521,0.614390,0.943896,1.940659,0.497827
min,29.000000,0.000000,1.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.00000,1.000000,0.000000,3.000000,1.000000
25%,48.000000,0.000000,3.000000,120.000000,213.000000,0.000000,0.000000,133.000000,0.000000,0.00000,1.000000,0.000000,3.000000,1.000000
50%,55.000000,1.000000,3.000000,130.000000,245.000000,0.000000,2.000000,153.500000,0.000000,0.80000,2.000000,0.000000,3.000000,1.000000
75%,61.000000,1.000000,4.000000,140.000000,280.000000,0.000000,2.000000,166.000000,1.000000,1.60000,2.000000,1.000000,7.000000,2.000000
max,77.000000,1.000000,4.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.20000,3.000000,3.000000,7.000000,2.000000

In [17]:
diagnosis = table['diagnosis']
diagnosis = diagnosis[:] -1
features = table.drop(columns="diagnosis")

nominals = ['chestpain','ecg','thal']
features_hot =  pd.get_dummies(features, columns=nominals)
features_hot.head()

,age,sex,restBP,chol,sugar,maxhr,angina,dep,exercise,fluor,chestpain_1.0,chestpain_2.0,chestpain_3.0,chestpain_4.0,ecg_0.0,ecg_1.0,ecg_2.0,thal_3.0,thal_6.0,thal_7.0
0,70.0,1.0,130.0,322.0,0.0,109.0,0.0,2.4,2.0,3.0,0,0,0,1,0,0,1,1,0,0
1,67.0,0.0,115.0,564.0,0.0,160.0,0.0,1.6,2.0,0.0,0,0,1,0,0,0,1,0,0,1
2,57.0,1.0,124.0,261.0,0.0,141.0,0.0,0.3,1.0,0.0,0,1,0,0,1,0,0,0,0,1
3,64.0,1.0,128.0,263.0,0.0,105.0,1.0,0.2,2.0,1.0,0,0,0,1,1,0,0,0,0,1
4,74.0,0.0,120.0,269.0,0.0,121.0,1.0,0.2,1.0,1.0,0,1,0,0,0,0,1,1,0,0

In [18]:

features_norm=(features_hot-features_hot.mean())/features_hot.std()
features_norm.describe()

,age,sex,restBP,chol,sugar,maxhr,angina,dep,exercise,fluor,chestpain_1.0,chestpain_2.0,chestpain_3.0,chestpain_4.0,ecg_0.0,ecg_1.0,ecg_2.0,thal_3.0,thal_6.0,thal_7.0
count,2.700000e+02,2.700000e+02,2.700000e+02,2.700000e+02,2.700000e+02,2.700000e+02,2.700000e+02,2.700000e+02,2.700000e+02,2.700000e+02,2.700000e+02,2.700000e+02,2.700000e+02,2.700000e+02,2.700000e+02,2.700000e+02,2.700000e+02,2.700000e+02,2.700000e+02,2.700000e+02
mean,3.708967e-16,5.263280e-17,5.781384e-16,-2.006625e-16,6.291264e-17,-4.934325e-18,2.417819e-16,3.264878e-16,-9.457455e-17,1.151342e-17,-1.661223e-16,1.439178e-17,-1.307596e-16,-1.052656e-16,8.470590e-17,-5.623074e-17,7.072532e-17,-1.093775e-16,-1.695146e-16,-1.891491e-17
std,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
min,-2.792090e+00,-1.447639e+00,-2.090766e+00,-2.392499e+00,-4.162558e-01,-3.396302e+00,-6.999225e-01,-9.168625e-01,-9.524656e-01,-7.102161e-01,-2.823184e-01,-4.284020e-01,-6.419351e-01,-9.547278e-01,-9.689972e-01,-8.622672e-02,-1.013045e+00,-1.132857e+00,-2.334201e-01,-7.900542e-01
25%,-7.062560e-01,-1.447639e+00,-6.351301e-01,-7.092654e-01,-4.162558e-01,-7.199336e-01,-6.999225e-01,-9.168625e-01,-9.524656e-01,-7.102161e-01,-2.823184e-01,-4.284020e-01,-6.419351e-01,-9.547278e-01,-9.689972e-01,-8.622672e-02,-1.013045e+00,-1.132857e+00,-2.334201e-01,-7.900542e-01
50%,6.220908e-02,6.882217e-01,-7.527007e-02,-9.014507e-02,-4.162558e-01,1.649948e-01,-6.999225e-01,-2.183006e-01,6.751655e-01,-7.102161e-01,-2.823184e-01,-4.284020e-01,-6.419351e-01,-9.547278e-01,-9.689972e-01,-8.622672e-02,9.834670e-01,8.794547e-01,-2.334201e-01,-7.900542e-01
75%,7.208935e-01,6.882217e-01,4.845899e-01,5.870178e-01,-4.162558e-01,7.045852e-01,1.423438e+00,4.802613e-01,6.751655e-01,3.492223e-01,-2.823184e-01,-4.284020e-01,1.552020e+00,1.043540e+00,1.028173e+00,-8.622672e-02,9.834670e-01,8.794547e-01,-2.334201e-01,1.261048e+00
max,2.477385e+00,6.882217e-01,3.843750e+00,6.081711e+00,2.393471e+00,2.258606e+00,1.423438e+00,4.496992e+00,2.302797e+00,2.468099e+00,3.528981e+00,2.325611e+00,1.552020e+00,1.043540e+00,1.028173e+00,1.155438e+01,9.834670e-01,8.794547e-01,4.268254e+00,1.261048e+00

In [7]:
# Save table without diagnosis
features_norm.to_csv('heart_features.csv', index=False)

In [8]:
features_norm['diagnosis'] = diagnosis
features_norm.to_csv('heart.csv', index=False)